# Generated by Django 5.0.6 on 2024-08-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_borrowbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
