# Generated by Django 5.0.6 on 2024-08-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_borrowbook_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
